<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2><?php echo $this->translate('Users') ?></h2>
            <p><a class="btn btn-success" href="<?php echo $this->url('users'); ?>" target="_blank"><?php echo $this->translate('Explore Users') ?> &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2><?php echo $this->translate('Roles') ?></h2>
            <p><a class="btn btn-success" href="<?php echo $this->url('roles'); ?>" target="_blank"><?php echo $this->translate('Explore Roles') ?> &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2><?php echo $this->translate('Resources') ?></h2>
            <p><a class="btn btn-success" href="<?php echo $this->url('resources'); ?>" target="_blank"><?php echo $this->translate('Explore Resources') ?> &raquo;</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2><?php echo $this->translate('Users &amp; Roles') ?></h2>
            <p><a class="btn btn-success" href="<?php echo $this->url('user_roles'); ?>" target="_blank"><?php echo $this->translate('Users &amp; Roles Mapping') ?> &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2><?php echo $this->translate('Roles &amp; Resources') ?></h2>
            <p><a class="btn btn-success" href="<?php echo $this->url('role_resources'); ?>" target="_blank"><?php echo $this->translate('Roles &amp; Resources Mapping') ?> &raquo;</a></p>
        </div>
    </div>
</div>