<div class="panel">
        <div class="panel-body">
        <?php

$title = 'Edit Resources';
$this->headTitle($title);
?>
<script type="text/javascript">
    /* <![CDATA[ */
    jQuery(function() {
        jQuery("#first_name").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Can not be empty"
        });
    });
    /* ]]> */
</script>
<div class="container">
    <div class="row">
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->partial('zf2auth/elements/message.phtml', array('flashMessages' => $this->flashMessages, 'error'         => $this->error)); ?>
<?php
$form  = $this->form;
$form->setAttribute('action', $this->url('resources/edit', array('id'     => $this->id,)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<table class="formtable">
<?php
foreach ($form as $element) :
        ?>
        <tr>
            <td><?php echo $element->getLabel(); ?></td>
            <td><?php
                if ($this->formElementErrors($element)) {
                    $element->setAttribute('class', 'required form-control ErrorField');
                }
                echo $this->formElement($element);
                if ($this->formElementErrors($element)):
                    ?>
                    <span class="ValidationErrors"><?php echo $this->formElementErrors($element); ?></span>
                    <?php
                endif;
                ?>
            </td>
        </tr>
        <?php
endforeach;
    ?>
    <tr>
            <td></td>
            <td><button class="btn btn-primary" type="submit">Submit</button>
            <button class="btn reset" type="reset" onclick="history.back();">Cancel</button></td>
        </tr>
</table>
<?php
echo $this->form()->closeTag();
?>
    </div>
</div>
    </div>
</div>
